### ISSUE TITLE
Launcher 2.0 to-do list

### ISSUE THREAD

**Issue by the-sane** [starcitizen-lug/knowledge-base#32]
- [x] Update our quickstart guide to instruct folks to install the latest wine-staging from the Kronek source that we already have in the Helper
- [x] Update news with the steps needed to migrate to the 2.0 launcher:
    - [x] Switch to wine-staging runner
    - [x] Enable CLI mode in lutris
